from enum import Enum


class CredentialType(str, Enum):
    
    RFID = "RFID"
    NFC = "NFC"
    QR_CODE = "QR_CODE"
    BIOMETRIA = "BIOMETRIA"


class AccessReason(str, Enum):
    """
    Status de acesso.
    """
    AUTORIZADO = "AUTORIZADO"
    UID_DESCONHECIDO = "UID_DESCONHECIDO"
    CREDENCIAL_INATIVA = "CREDENCIAL_INATIVA"
    TIPO_CREDENCIAL_INVALIDO = "TIPO_CREDENCIAL_INVALIDO"
    USUARIO_INATIVO = "USUARIO_INATIVO"
    USUARIO_DESCONHECIDO = "USUARIO_DESCONHECIDO"
    SEM_PERMISSAO = "SEM_PERMISSAO"
    PORTA_INATIVA = "PORTA_INATIVA"
    PORTA_DESCONHECIDA = "PORTA_DESCONHECIDA"
    DISPOSITIVO_INATIVO = "DISPOSITIVO_INATIVO"
    DISPOSITIVO_DESCONHECIDO = "DISPOSITIVO_DESCONHECIDO"
    PORTA_NAO_PERTENCE_AO_DISPOSITIVO = "PORTA_NAO_PERTENCE_AO_DISPOSITIVO"
    ERRO_DE_LEITURA = "ERRO_DE_LEITURA"
    ERRO_INTERNO = "ERRO_INTERNO"
    
