// módulo usado para transformar o loop em uma máquina de estados

#ifndef STATE_CONTROL_H
#define STATE_CONTROL_H

enum StateControl
{
    INICIALIZANDO,
    CONECTANDO_WIFI,
    AGUARDANDO_CREDENCIAL,
    AUTENTICANDO,
    ACESSO_AUTORIZADO,
    ACESSO_NEGADO,
    ERRO_DE_COMUNICACAO
};


// enum class AccessReason
// {
//     AUTORIZADO,
//     UID_DESCONHECIDO,
//     CREDENCIAL_INATIVA,
//     TIPO_CREDENCIAL_INVALIDO,
//     USUARIO_INATIVO,
//     USUARIO_DESCONHECIDO,
//     SEM_PERMISSAO,
//     PORTA_INATIVA,
//     PORTA_DESCONHECIDA,
//     DISPOSITIVO_INATIVO,
//     DISPOSITIVO_DESCONHECIDO,
//     PORTA_NAO_PERTENCE_AO_DISPOSITIVO,
//     ERRO_DE_LEITURA,
//     ERRO_INTERNO
// }

#endif